### ISSUE TITLE
获取缓存的疑问

### ISSUE THREAD

**Issue by bowenpz** [Pacific73/gorm-cache#12]
https://github.com/Pacific73/gorm-cache/blob/1d0b034dd8c711a96fbd9e19568b6d5a0b195cda/cache/before_query.go#L28

现在的代码实现里，在 before_query 查 key 是否存在，在 after_query 里查 value，感觉会出现一种情况，查 key 的时候查到了，然后缓存过期了，再查 value 的时候失败了。

为什么不在 before_query 的时候直接查，放到 context 里传下去呢，还可以少一次查询操作，是我哪里没考虑到吗

**Comment by Pacific73** [comment]
同#14，本issue关闭
