### ISSUE TITLE
before_query 查到缓存 key 存在，可能会在 after_query 前过期

### ISSUE THREAD

**Issue by bowenpz** [Pacific73/gorm-cache#14]
https://github.com/Pacific73/gorm-cache/blob/1d0b034dd8c711a96fbd9e19568b6d5a0b195cda/cache/after_query.go#L101

缓存有过期时间，如果碰巧在 after_query 前过期，那就会查不到

**Comment by bowenpz** [comment]
提两个个人建议哈
- before_query 直接查缓存，放到上下文里传下去
- before_query 做一下防缓存击穿，缓存过期的时候 db 扛不住的

**Comment by Pacific73** [comment]
谢谢你的建议，这些建议均已实现，请使用最新版
