### ISSUE TITLE
如果直接传 cache key 是不是也行

### ISSUE THREAD

**Issue by bowenpz** [Pacific73/gorm-cache#15]
https://github.com/Pacific73/gorm-cache/blob/229ea3b5728e11ce194163f7a5512053ee7f2c6a/cache/after_query.go#L23-L26

看了下 sql 和 vars 好像只用在打印日志和生成 key 上，如果直接在 before_query 拼接好 key 然后传过去呢，个人想法哈

**Comment by Pacific73** [comment]
我理解都是可以的。个人认为分开传有助于理解代码
