### ISSUE TITLE
Can gorm-cache support Raw SQL operations?

### ISSUE THREAD

**Issue by rts-gordon** [Pacific73/gorm-cache#18]
Hi @Pacific73 
   Gorm-cache is a great project, but it can't support Raw SQL operations, may I get the reason?

  Is there any plan to support Raw SQL operations in feature?  Thank you.

**Comment by Pacific73** [comment]
Sorry, we won't support raw sql execution cache. It's not because we don't have time, it's not feasible in theory instead. We cache queried models via json marshaling, while raw sql executions bring us sql.Row or sql.Rows struct, which cannot be cached via json marshaling.

**Comment by rts-gordon** [comment]
Thanks for your explain.
