### ISSUE TITLE
Why there are two tiers for cache?

### ISSUE THREAD

**Issue by rts-gordon** [Pacific73/gorm-cache#19]
Hi @Pacific73 
  I am studying gorm-cache, I noticed there are two tier caches: one is remote Redis, another is local memory. 
  Why design a two-tier cache? This makes the design more complex, will it improve performance?

  Can I use the remote Redis only ? or use the local memory only?

  Thank you.

**Comment by Pacific73** [comment]
They're not like 2-tier relationship, instead you can use redis as cache storage OR local memory. They're EITHER-OR relationship.

**Comment by rts-gordon** [comment]
Got it. Thanks a lot.
