### ISSUE TITLE
Upgrade dependencies: go-redis and ccache

### ISSUE THREAD

**Issue by rts-gordon** [Pacific73/gorm-cache#21]
Hi @Pacific73 
  Would you like to upgrade some dependencies to latest version, they are a bit old.  Thank you.

  go-redis: v6-->v8
  ccache: v2-->v3

**Comment by Pacific73** [comment]
For some compatibility issue, we tend not to upgrade the version. If you really need this feature, you can fork and modify the code. Thx

**Comment by asjdf** [comment]
I'm curious to see if the new lib version will provide a performance boost.
