### ISSUE TITLE
关于CacheMaxItemCnt

### ISSUE THREAD

**Issue by xcel3011** [Pacific73/gorm-cache#27]
// CacheMaxItemCnt for given query, if objects retrieved are more than this cnt,
	// then we choose not to cache for this query. 0 represents caching all queries.
	CacheMaxItemCnt int64
	
	注释里写着0表示缓存所有，但是判断的时候好像没特殊判断0。
	// cache search data
	if int64(len(objects)) > cache.Config.CacheMaxItemCnt {
		return
	}

**Comment by Pacific73** [comment]
感谢建议，最新版本中已经修复。
