### ISSUE TITLE
并发情况下处理耗时慢慢累积，最终超时

### ISSUE THREAD

**Issue by fonoisrev** [Pacific73/gorm-cache#29]
版本v1.1.0

使用内存缓存，如下配置
```go
       cache.NewGorm2Cache(&config.CacheConfig{
		CacheLevel:           config.CacheLevelAll,
		CacheStorage:         config.CacheStorageMemory,
		InvalidateWhenUpdate: true,  // when you create/update/delete objects, invalidate cache
		CacheTTL:             10000, // 10s
		CacheSize:            5000,
		// exceeds this number, then don't cache
	}
```

AfterUpdate方法耗时会慢慢累积，最终会导致数据读写操作均超时

以下是go trace看到的结果

首先可以看到AfterUpdate是耗时大户
<img width="1331" alt="image" src="https://github.com/Pacific73/gorm-cache/assets/2321796/ce71fecd-8739-46a0-b771-87e9d0009e14">

大量的goroutine在AfterUpdate
<img width="696" alt="image" src="https://github.com/Pacific73/gorm-cache/assets/2321796/e983f1bc-dc81-47e7-b99c-1ffedea7dfba">

scheduler wait
<img width="1208" alt="image" src="https://github.com/Pacific73/gorm-cache/assets/2321796/071150b8-6e1f-4c99-b653-29a5c27c0319">

可以看到阻塞在写channel
<img width="1108" alt="image" src="https://github.com/Pacific73/gorm-cache/assets/2321796/d55ceb83-8b5d-4733-acda-6be35859acca">

对应的代码
<img width="945" alt="image" src="https://github.com/Pacific73/gorm-cache/assets/2321796/e6b6f2f1-cdb9-404e-981d-8c8e501fce9f">

这里为什么采用deletables chan *Item这样的设计？

**Comment by Pacific73** [comment]
感谢楼上asjdf的评论，如果是因为ccache包的问题，您可以自行fork替换一下cache层的实现。我因为日常工作繁忙，投入时间不会很多。欢迎提交pr!
